# Generated by Django 4.2.3 on 2023-07-08 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('pib', models.IntegerField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=100)),
                ('Adresa', models.CharField(max_length=100)),
                ('Djelatnost', models.CharField(max_length=100)),
                ('Podrucna_Jedinica', models.CharField(max_length=100)),
                ('Datum_reg', models.DateField()),
                ('Reg_br', models.CharField(max_length=100)),
                ('Mesto_reg', models.CharField(max_length=100)),
                ('Registrovan_PDV', models.BooleanField()),
                ('Datum_PDV', models.DateField(null=True)),
                ('Broj_PDV', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Iskaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_iskaza', models.CharField(max_length=100)),
                ('godina', models.IntegerField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.firma')),
            ],
        ),
    ]
