# Generated by Django 4.2.3 on 2023-07-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_adresa_firma_adresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='Broj_PDV',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='firma',
            name='Mesto_reg',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='firma',
            name='Reg_br',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='firma',
            name='adresa',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='firma',
            name='djelatnost',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='firma',
            name='naziv',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='firma',
            name='podrucna_Jedinica',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='iskaz',
            name='broj_iskaza',
            field=models.CharField(max_length=256),
        ),
    ]
