# Generated by Django 4.2.3 on 2023-07-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_firma_broj_pdv_alter_firma_mesto_reg_and_more'),
    ]

    operations = [
    ]
