# Generated by Django 4.2.3 on 2023-07-19 17:09

from django.db import migrations

from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20230719_1908'),
    ]

    operations = [
        UnaccentExtension()
    ]
